apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://dev.azure.com/VenkateshKalluri/ArgoCD-voting%20app/_git/ArgoCD-voting%20app?path=%2F&version=GBmain&_a=contents'
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: voting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true