trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  ACR_NAME: argocdregistry
  ACR_LOGIN_SERVER: argocdregistry.azurecr.io
  IMAGE_NAME: voting-app   # change to worker-app if building worker service

stages:
- stage: BuildAndPush
  jobs:
  - job: DockerBuild
    steps:
    - checkout: self
      persistCredentials: true   # ✅ allows Git push to repo

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'argocd_sc'   # replace with your ACR service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logging into ACR..."
          az acr login --name $(ACR_NAME)

          echo "Building Docker image..."
          # 👉 Fix: specify correct Dockerfile path + context
          docker build -f vote/Dockerfile -t $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId) vote/

          echo "Pushing Docker image..."
          docker push $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(Build.BuildId)

    - script: |
        chmod +x update_manifest.sh
        ./update_manifest.sh $(ACR_LOGIN_SERVER)/$(IMAGE_NAME) $(Build.BuildId) $(Build.SourceBranchName)
      displayName: "Update Kubernetes manifest"