apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: worker-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/venkatesh-neu/Voting-app.git'
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: voting
  syncPolicy:
    automated:
      prune: true
      selfHeal: false